# Generated by Django 3.0.6 on 2020-05-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tz', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('activityby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapiapp.User')),
            ],
        ),
    ]
